package diexun.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutouploadLogicPort", targetNamespace = "urn:AutouploadLogic")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AutouploadLogicPort {


    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#createFolder")
    @WebResult(name = "createFolder", partName = "createFolder")
    public String createFolder(
        @WebParam(name = "_args", partName = "_args")
        String args);

    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#addSubject")
    @WebResult(name = "addSubject", partName = "addSubject")
    public String addSubject(
        @WebParam(name = "args", partName = "args")
        String args);

    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#addSubsidiary")
    @WebResult(name = "addSubsidiary", partName = "addSubsidiary")
    public String addSubsidiary(
        @WebParam(name = "args", partName = "args")
        String args);

    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#addPicture")
    @WebResult(name = "addPicture", partName = "addPicture")
    public String addPicture(
        @WebParam(name = "args", partName = "args")
        String args);

    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#addFolder")
    @WebResult(name = "addFolder", partName = "addFolder")
    public String addFolder(
        @WebParam(name = "args", partName = "args")
        String args);

    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#addFolderSubject")
    @WebResult(name = "addFolderSubject", partName = "addFolderSubject")
    public String addFolderSubject(
        @WebParam(name = "args", partName = "args")
        String args);

    /**
     * 
     * @param args
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#addAnalysis")
    @WebResult(name = "addAnalysis", partName = "addAnalysis")
    public String addAnalysis(
        @WebParam(name = "args", partName = "args")
        String args);

    /**
     * 
     * @param authcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:AutouploadLogic#Webserver\\Logic\\AutouploadLogic#auth")
    @WebResult(name = "auth", partName = "auth")
    public String auth(
        @WebParam(name = "authcode", partName = "authcode")
        String authcode);

}
