package diexun.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutouploadLogic", targetNamespace = "urn:AutouploadLogic")
public class AutouploadLogic
    extends Service
{

    private final static URL AUTOUPLOADLOGIC_WSDL_LOCATION;
    private final static WebServiceException AUTOUPLOADLOGIC_EXCEPTION;
    private final static QName AUTOUPLOADLOGIC_QNAME = new QName("urn:AutouploadLogic", "AutouploadLogic");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://service.manager.diexun.cc/Server/autoupload?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTOUPLOADLOGIC_WSDL_LOCATION = url;
        AUTOUPLOADLOGIC_EXCEPTION = e;
    }

    public AutouploadLogic() {
        super(__getWsdlLocation(), AUTOUPLOADLOGIC_QNAME);
    }

    public AutouploadLogic(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOUPLOADLOGIC_QNAME, features);
    }

    public AutouploadLogic(URL wsdlLocation) {
        super(wsdlLocation, AUTOUPLOADLOGIC_QNAME);
    }

    public AutouploadLogic(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOUPLOADLOGIC_QNAME, features);
    }

    public AutouploadLogic(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutouploadLogic(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutouploadLogicPort
     */
    @WebEndpoint(name = "AutouploadLogicPort")
    public AutouploadLogicPort getAutouploadLogicPort() {
        return super.getPort(new QName("urn:AutouploadLogic", "AutouploadLogicPort"), AutouploadLogicPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutouploadLogicPort
     */
    @WebEndpoint(name = "AutouploadLogicPort")
    public AutouploadLogicPort getAutouploadLogicPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:AutouploadLogic", "AutouploadLogicPort"), AutouploadLogicPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOUPLOADLOGIC_EXCEPTION!= null) {
            throw AUTOUPLOADLOGIC_EXCEPTION;
        }
        return AUTOUPLOADLOGIC_WSDL_LOCATION;
    }

}
