package diexun.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetattrinfoLogic", targetNamespace = "urn:GetattrinfoLogic")
public class GetattrinfoLogic
    extends Service
{

    private final static URL GETATTRINFOLOGIC_WSDL_LOCATION;
    private final static WebServiceException GETATTRINFOLOGIC_EXCEPTION;
    private final static QName GETATTRINFOLOGIC_QNAME = new QName("urn:GetattrinfoLogic", "GetattrinfoLogic");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://service.manager.diexun.cc/Server/getattrinfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETATTRINFOLOGIC_WSDL_LOCATION = url;
        GETATTRINFOLOGIC_EXCEPTION = e;
    }

    public GetattrinfoLogic() {
        super(__getWsdlLocation(), GETATTRINFOLOGIC_QNAME);
    }

    public GetattrinfoLogic(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETATTRINFOLOGIC_QNAME, features);
    }

    public GetattrinfoLogic(URL wsdlLocation) {
        super(wsdlLocation, GETATTRINFOLOGIC_QNAME);
    }

    public GetattrinfoLogic(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETATTRINFOLOGIC_QNAME, features);
    }

    public GetattrinfoLogic(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetattrinfoLogic(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetattrinfoLogicPort
     */
    @WebEndpoint(name = "GetattrinfoLogicPort")
    public GetattrinfoLogicPort getGetattrinfoLogicPort() {
        return super.getPort(new QName("urn:GetattrinfoLogic", "GetattrinfoLogicPort"), GetattrinfoLogicPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetattrinfoLogicPort
     */
    @WebEndpoint(name = "GetattrinfoLogicPort")
    public GetattrinfoLogicPort getGetattrinfoLogicPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:GetattrinfoLogic", "GetattrinfoLogicPort"), GetattrinfoLogicPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETATTRINFOLOGIC_EXCEPTION!= null) {
            throw GETATTRINFOLOGIC_EXCEPTION;
        }
        return GETATTRINFOLOGIC_WSDL_LOCATION;
    }

}
