package diexun.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetattrinfoLogicPort", targetNamespace = "urn:GetattrinfoLogic")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface GetattrinfoLogicPort {


    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:GetattrinfoLogic#Webserver\\Logic\\GetattrinfoLogic#getAttrInfoByLable")
    @WebResult(name = "getAttrInfoByLable", partName = "getAttrInfoByLable")
    public String getAttrInfoByLable(
        @WebParam(name = "parameter", partName = "parameter")
        String parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:GetattrinfoLogic#Webserver\\Logic\\GetattrinfoLogic#getAttrInfoById")
    @WebResult(name = "getAttrInfoById", partName = "getAttrInfoById")
    public String getAttrInfoById(
        @WebParam(name = "parameter", partName = "parameter")
        String parameter);

    /**
     * 
     * @param parameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:GetattrinfoLogic#Webserver\\Logic\\GetattrinfoLogic#getAttrInfoByName")
    @WebResult(name = "getAttrInfoByName", partName = "getAttrInfoByName")
    public String getAttrInfoByName(
        @WebParam(name = "parameter", partName = "parameter")
        String parameter);

    /**
     * 
     * @param authcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:GetattrinfoLogic#Webserver\\Logic\\GetattrinfoLogic#auth")
    @WebResult(name = "auth", partName = "auth")
    public String auth(
        @WebParam(name = "authcode", partName = "authcode")
        String authcode);

}
